import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const houseList = [
  {
	id: "1b796a7b-b224-4894-91a6-296d4d218d50",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
	title: "Lovely House",
	houseNumber: 40,
	streetName: "Herzogstraße",
    city: "wuppertal",
	postalCode: 42103,
	country: "Germany",
    lat: 51.257180,
    lng: 7.142770,
	owner: "Sam Colin",
	price: 290,
	size: 15,
	heating: false,
	cooling: false,
	rooms: 2,
	caution: 500,
	supermarktDistance: 800,
	busStationDistance: 900,
	maxResident: 1,
	furnished: false,
	parking: false,
  },
  {
	id: "4018906b-0647-458f-8349-73f48341d9ef",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680445489/yvhpeizk/dwdolz4smxca4nsmeeao.png",
	title: "Lovely House with balcony",
    houseNumber: 14,
	streetName: "Baumeisterstraße",
    city: "wuppertal",
	postalCode: 42105,
	country: "Germany",
    lat: 51.265390,
    lng: 7.132650,
	owner: "Joe Rogan",
	price: 350,
	size: 20,
	heating: true,
	cooling: false,
	rooms: 3,
	caution: 200,
	supermarktDistance: 500,
	busStationDistance: 600,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
  {
	id: "d569601b-e180-4e7c-acb5-5c521ed8da92",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680445489/yvhpeizk/dwdolz4smxca4nsmeeao.png",
	title: "Lovely house in city center",
    houseNumber: 1,
	streetName: "Teichstraße",
    city: "Essen",
	postalCode: 45127,
	country: "Germany",
    lat: 51.454630,
    lng: 7.015190,
	owner: "Sam Colin",
	price: 430,
	size: 30,
	heating: true,
	cooling: false,
	rooms: 2,
	caution: 1000,
	supermarktDistance: 1100,
	busStationDistance: 1200,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
  {
	id: "2bd2f903-6a86-4903-8404-3848adf1dce1",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
	title: "Ghosted House",
    houseNumber: 5,
	streetName: "Huyssenallee",
    city: "Essen",
	postalCode: 45128,
	country: "Germany",
    lat: 51.449120,
    lng: 7.012210,
	owner: "Sam Colin",
	price: 350,
	size: 20,
	heating: true,
	cooling: false,
	rooms: 3,
	caution: 200,
	supermarktDistance: 500,
	busStationDistance: 600,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
  {
	id: "1780ebbf-58b2-4d2e-af30-aecd159d7c3b",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680445489/yvhpeizk/dwdolz4smxca4nsmeeao.png",
	title: "The Hogwarts",
    houseNumber: 2,
	streetName: "Görresstraße",
    city: "Cologne",
	postalCode: 50674,
	country: "Germany",
    lat: 50.9312944,
    lng: 6.9347885,
	owner: "Sam Colin",
	price: 250,
	size: 12,
	heating: true,
	cooling: false,
	rooms: 1,
	caution: 600,
	supermarktDistance: 1500,
	busStationDistance: 1400,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
  {
	id: "031b64e2-8df8-477d-83a9-271e53a2480f",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
	title: "The Villa",
	houseNumber: 53,
    streetName: "Kyffhäuserstraße",
    city: "Cologne",
	postalCode: 50674,
	country: "Germany",
    lat: 50.9283856,
    lng: 6.9373138,
	owner: "Sam Colin",
	price: 350,
	size: 20,
	heating: true,
	cooling: false,
	rooms: 3,
	caution: 200,
	supermarktDistance: 500,
	busStationDistance: 600,
	maxResident: 1,
	furnished: true,
	parking: false,
  },
  {
	id: "242dce14-345b-4332-b70b-67bb0d2ca156",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
	title: "Just a house",
    houseNumber: 23,
    streetName: "Rathausstraße",
    city: "Berlin",
	postalCode: 10178,
	country: "Germany",
    lat: 52.517437,
    lng: 13.4053296,
	owner: "Joe Biden",
	price: 660,
	size: 18,
	heating: true,
	cooling: false,
	rooms: 1,
	caution: 2000,
	supermarktDistance: 500,
	busStationDistance: 600,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
  {
	id: "2cafc220-0bd3-4c1d-938a-4a599a249701",
	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680445489/yvhpeizk/dwdolz4smxca4nsmeeao.png",
	title: "White House",
    houseNumber: 44,
    streetName: "Bayreuther",
    city: "Berlin",
	postalCode: 10787,
	country: "Germany",
    lat: 52.5036605,
    lng: 13.3445085,
	owner: "Lex Friedman",
	price: 350,
	size: 30,
	heating: true,
	cooling: false,
	rooms: 3,
	caution: 200,
	supermarktDistance: 500,
	busStationDistance: 600,
	maxResident: 3,
	furnished: true,
	parking: false,
  },
//  {
//	id: "1d1b96a7-629e-4a27-8fb0-9f07a47a416d",
//	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
//	title: "Little Sunshine",
//    place: "essen",
//    lat: 51.455947,
//    lng: 7.012842,
//	owner: "Sam Colin",
//	price: 350,
//	size: 20,
//	heating: true,
//	cooling: false,
//	rooms: 3,
//	caution: 200,
//	supermarktDistance: 500,
//	busStationDistance: 600,
//	maxResident: 3,
//	furnished: true,
//	parking: false,
//  },
//  {
//	id: "d204b730-10bd-40fc-a9d1-17f8c00cfb1d",
//	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
//	title: "The Corner",
//    place: "berlin",
//    lat: 52.521049,
//    lng: 13.406402,
//	owner: "Lex Friedman",
//	price: 350,
//	size: 20,
//	heating: true,
//	cooling: false,
//	rooms: 3,
//	caution: 200,
//	supermarktDistance: 500,
//	busStationDistance: 600,
//	maxResident: 3,
//	furnished: true,
//	parking: false,
//  },
//  {
//	id: "cc25f8ff-0369-45cd-a2db-e1fbe595bb52",
//	imageUrl: "https://res.cloudinary.com/dxlbetitl/image/upload/v1680432896/yvhpeizk/mnb8rjovcqqd6puackzu.png",
//	title: "The Haunted House",
//    place: "test",
//    lat: 52.451049,
//    lng: 13.406402,
//	owner: "Joe Rogan",
//	price: 350,
//	size: 20,
//	heating: true,
//	cooling: false,
//	rooms: 3,
//	caution: 200,
//	supermarktDistance: 500,
//	busStationDistance: 600,
//	maxResident: 3,
//	furnished: true,
//	parking: false,
//  },
];

const seekerList = [
  {
	name: "Chuck Norris",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: true,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Natalie Portman",
	profession: "Actor",
	age: 30,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 400,
	hobby: "Acting",
	pet: true,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Mike Tyson",
	profession: "Studen",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 350,
	hobby: "Cricket",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: false,
  },
  {
	name: "Manuel Neuer",
	profession: "Student",
	age: 23,
	nationality: "German",
	language: "German",
	howMuchWannaSpend: 300,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "David Noah",
	profession: "Engineer",
	age: 30,
	nationality: "German",
	language: "German",
	howMuchWannaSpend: 400,
	hobby: "Comedy",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Marco Polo",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Timo Tyler",
	profession: "Student",
	age: 23,
	nationality: "German",
	language: "German",
	howMuchWannaSpend: 300,
	hobby: "Cricket",
	pet: false,
	allergie: true,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "David Guetta",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 8,
	smoker: true,
  },
  {
	name: "Harrison Ford",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: true,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Emilie Clarke",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Joe Greer",
	profession: "Student",
	age: 23,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: true,
	monthsOfStay: 6,
	smoker: true,
  },
  {
	name: "Isla Fisher",
	profession: "Student",
	age: 23,
	nationality: "Arab",
	language: "Arab",
	howMuchWannaSpend: 350,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
  {
	name: "Jessica Biel",
	profession: "Driver",
	age: 22,
	nationality: "Polish",
	language: "Polish",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 6,
	smoker: true,
  },
  {
	name: "Jennifer Lawrence",
	profession: "Student",
	age: 27,
	nationality: "American",
	language: "English",
	howMuchWannaSpend: 320,
	hobby: "Movie",
	pet: false,
	allergie: false,
	monthsOfStay: 15,
	smoker: true,
  },
  {
	name: "Richerd Wagner",
	profession: "Student",
	age: 25,
	nationality: "Arab",
	language: "Arabic",
	howMuchWannaSpend: 320,
	hobby: "Football",
	pet: false,
	allergie: false,
	monthsOfStay: 12,
	smoker: true,
  },
];

async function main() {
  // await prisma.houses.create({
  //   data: { place: "wuppertal", latlng: { lat: 51.256692, lng: 7.149697 } },
  // });

  await prisma.houses.createMany({
    data: houseList,
  });

  await prisma.seekers.createMany(
	{
		data: seekerList,
	}
  );
}
main()
  .then(async () => {
    await prisma.$disconnect();
    console.log("Database seed complete!");
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
